import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { SigmaGraph } from "../components/DepsGraph";
import { asyncComponent } from "react-async-component";

const myGraph: SigmaGraph = {
  nodes: [
    { id: "n1", label: "Alice" },
    { id: "n2", label: "Rabbit" }
  ],
  edges: [{ id: "e1", source: "n1", target: "n2", label: "SEES" }]
};

export default function Home() {
  const [graphData, setGraphData] = useState<SigmaGraph>();
  useEffect(() => {
    setGraphData(myGraph);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Source Timeline</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AsyncGraph data={graphData!} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

const AsyncGraph = asyncComponent({
  resolve: () => import("../components/DepsGraph"),
  LoadingComponent: () => <div>Loading...</div>, // Optional
  ErrorComponent: ({ error }) => <div>{error.message}</div> // Optional
});
