import Head from "next/head";
import Image from "next/image";
import { useEffect, useState} from "react";
import styles from "../styles/Home.module.css";
import { SigmaGraph } from "../components/DepsGraph";
import dynamic from 'next/dynamic'

export default function Home() {
  const [graphData, setGraphData] = useState<SigmaGraph>();
  useEffect(() => {
    fetch("/api/hello")
      .then(r => r.json())
      .then(r => {
        setGraphData(r);
      });
  }, []);

  const DepsGraph = dynamic(() => import('../components/DepsGraph'),{ loading: () => <Spinner/> })

  return (
    <div className={styles.container}>
      <Head>
        <title>Source Timeline</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      {
        graphData && (<DepsGraph data={graphData}/>)
      }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

function Spinner(){
  return <div>Loading...</div>
}
