import Head from "next/head";
import { useEffect, useState} from "react";
import styles from "../styles/Home.module.css";
import { SigmaGraph } from "../components/DepsGraph";
import dynamic from 'next/dynamic'
import {toGraph} from '../utils/graphology'
import type Graph from 'graphology'

export default function Home() {
  const [graphData, setGraphData] = useState<Graph>();
  useEffect(() => {
    fetch("/api/hello")
      .then(r => r.json())
      .then(r => {
        setGraphData(toGraph(r as SigmaGraph));
      });
  }, []);

  const DepsGraph = dynamic(() => import('../components/MatterGraph'),{ loading: () => <Spinner/> })

  return (
    <div className={styles.container}>
      <Head>
        <title>Source Timeline</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      {
        graphData && (<DepsGraph data={graphData}/>)
      }
      </main>
    </div>
  );
}

function Spinner(){
  return <div>Loading...</div>
}
